name: vae
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - python=3.10.9
  - pip
  - black
  - pytorch=2.0.0
  - torchvision
  - torchaudio
  - pytorch-cuda=11.8
  - numpy=1.23.5
  - ipython
  - ipykernel
  - ipywidgets
  - colorama
  - matplotlib
  - tqdm
  - pip:
    - torchviz # Requires graphviz (sudo apt install -y graphviz)
